spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    cassandra:
      port: 9003
jwt:
  secret-key : ${SECRET_KEY}
  access-token-expire-time : 3600
  refresh-token-expire-time : 7200
aligo :
  key : ${ALIGO_KEY}
  send-url : https://apis.aligo.in/send/
  send-phone-number: ${ALIGO_SEND_PHONE_NUMBER}